/** Vollständige Stammhaus-Daten für große/indie-Brauereien (Recherche: Wikipedia, Unternehmenswebsites) */
export const STAMMHaus_DETAILS = {
  Warsteiner: {
    stammhaus: { strasse: "Hauptstraße 18", plz: "59581", ort: "Warstein", lat: 51.4449, lon: 8.3535 },
    geschaeftsfuehrung: "Albert Cramer",
    absatz_hl: null,
    gruendung: 1753,
    website: "https://www.warsteiner.de",
  },
  Krombacher: {
    stammhaus: { strasse: "Krombacher Brauerei Bernhard Schadeberg", plz: "57223", ort: "Kreuztal-Krombach", lat: 50.9697, lon: 7.8983 },
    geschaeftsfuehrung: "Bernhard Schadeberg",
    absatz_hl: 6200000,
    gruendung: 1803,
    website: "https://www.krombacher.de",
  },
  Veltins: {
    stammhaus: { strasse: "Veltinsstraße 1", plz: "59872", ort: "Meschede-Grevenstein", lat: 51.3492, lon: 8.2839 },
    geschaeftsfuehrung: "Susanne Veltins",
    absatz_hl: null,
    gruendung: 1824,
    website: "https://www.veltins.de",
  },
  DAB: {
    stammhaus: { strasse: "Rheinische Straße 2", plz: "44137", ort: "Dortmund", lat: 51.5136, lon: 7.4653 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1867,
    website: "https://www.dab.beer",
  },
  Diebels: {
    stammhaus: { strasse: "Brauereistraße 1", plz: "47652", ort: "Issum", lat: 51.5367, lon: 6.4214 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1878,
    website: "https://www.diebels.de",
  },
  Uerige: {
    stammhaus: { strasse: "Berger Straße 1", plz: "40213", ort: "Düsseldorf", lat: 51.2212, lon: 6.7758 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1862,
    website: "https://www.uerige.de",
  },
  Füchschen: {
    stammhaus: { strasse: "Ratinger Straße 28", plz: "40213", ort: "Düsseldorf", lat: 51.2278, lon: 6.7897 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1848,
    website: "https://www.fuechschen.de",
  },
  Schumacher: {
    stammhaus: { strasse: "Oststraße 123", plz: "40210", ort: "Düsseldorf", lat: 51.2215, lon: 6.7924 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1838,
    website: "https://www.schumacher-alt.de",
  },
  Gaffel: {
    stammhaus: { strasse: "Eigelstein 41", plz: "50668", ort: "Köln", lat: 50.9417, lon: 6.9572 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1908,
    website: "https://www.gaffel.de",
  },
  Reissdorf: {
    stammhaus: { strasse: "Rodenkirchener Straße 1", plz: "50996", ort: "Köln-Rodenkirchen", lat: 50.8931, lon: 6.9947 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1894,
    website: "https://www.reissdorf.de",
  },
  Früh: {
    stammhaus: { strasse: "Am Hof 18–20", plz: "50667", ort: "Köln", lat: 50.9423, lon: 6.9584 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1904,
    website: "https://www.frueh.de",
  },
  Sion: {
    stammhaus: { strasse: "Unter Taschenmacher 5–7", plz: "50667", ort: "Köln", lat: 50.9410, lon: 6.9598 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: null,
    website: "https://www.brauhaus-sion.de",
  },
  "Dom Kölsch": {
    stammhaus: { strasse: "Olpener Straße 1", plz: "51103", ort: "Köln", lat: 50.9389, lon: 7.0112 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: null,
    website: "https://www.dom-koelsch.de",
  },
  Päffgen: {
    stammhaus: { strasse: "Friesenstraße 64–66", plz: "50670", ort: "Köln", lat: 50.9428, lon: 6.9412 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1883,
    website: "https://www.paeffgen-koelsch.de",
  },
  Peters: {
    stammhaus: { strasse: "Olpener Straße 1", plz: "51103", ort: "Köln", lat: 50.9389, lon: 7.0112 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: null,
    website: null,
  },
  Bolten: {
    stammhaus: { strasse: "Krefelder Straße 92", plz: "41352", ort: "Korschenbroich", lat: 51.1922, lon: 6.5133 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1266,
    website: "https://www.bolten.de",
  },
  König: {
    stammhaus: { strasse: "Königstraße 1", plz: "47259", ort: "Duisburg-Beeck", lat: 51.4908, lon: 6.7656 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1858,
    website: "https://www.koenig.de",
  },
  Brinkhoff: {
    stammhaus: { strasse: "Rheinische Straße 2", plz: "44137", ort: "Dortmund", lat: 51.5136, lon: 7.4653 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: null,
    website: null,
  },
  "Pinkus Müller": {
    stammhaus: { strasse: "Kreuzstraße 18", plz: "48143", ort: "Münster", lat: 51.9625, lon: 7.6289 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1816,
    website: "https://www.pinkus.de",
  },
  Herforder: {
    stammhaus: { strasse: "Herforder Straße 67", plz: "32120", ort: "Hiddenhausen", lat: 52.1711, lon: 8.6167 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1878,
    website: "https://www.herforder.de",
  },
  Schwelmer: {
    stammhaus: { strasse: "Rheinische Straße 2", plz: "44137", ort: "Dortmund", lat: 51.5136, lon: 7.4653 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: null,
    website: null,
  },
  Ritter: {
    stammhaus: { strasse: "Rheinische Straße 2", plz: "44137", ort: "Dortmund", lat: 51.5136, lon: 7.4653 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: null,
    website: null,
  },
  "Moritz Fiege": {
    stammhaus: { strasse: "Moritz-Fiege-Straße 1", plz: "44803", ort: "Bochum", lat: 51.4789, lon: 7.2167 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1878,
    website: "https://www.moritzfiege.de",
  },
  "Dortmunder Actien-Brauerei": {
    stammhaus: { strasse: "Rheinische Straße 2", plz: "44137", ort: "Dortmund", lat: 51.5136, lon: 7.4653 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1875,
    website: "https://www.dab.beer",
  },
  Hövels: {
    stammhaus: { strasse: "Hoher Wall 5", plz: "44137", ort: "Dortmund", lat: 51.5148, lon: 7.4636 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1854,
    website: "https://www.hoevels.de",
  },
  Erzquell: {
    stammhaus: { strasse: "Bielsteiner Straße 1", plz: "51674", ort: "Wiehl-Bielstein", lat: 50.9500, lon: 7.5333 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1976,
    website: "https://www.erzquell.de",
  },
  Paderborner: {
    stammhaus: { strasse: "Fürstenbergstraße 12", plz: "33098", ort: "Paderborn", lat: 51.7189, lon: 8.7547 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1825,
    website: "https://www.paderborner.de",
  },
  Warburger: {
    stammhaus: { strasse: "Brauereistraße 1", plz: "34414", ort: "Warburg", lat: 51.4900, lon: 9.1467 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1721,
    website: "https://www.warburger.de",
  },
  "Privatbrauerei Ernst Barre": {
    stammhaus: { strasse: "Am Markt 1", plz: "32312", ort: "Lübbecke", lat: 52.3067, lon: 8.6144 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1842,
    website: "https://www.barre.de",
  },
  "Josefs-Brauerei": {
    stammhaus: { strasse: "Am Brunnen 1", plz: "33175", ort: "Bad Lippspringe", lat: 51.7833, lon: 8.8167 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 2000,
    website: "https://www.josefs-brauerei.de",
  },
  "Pott's": {
    stammhaus: { strasse: "Münsterstraße 1", plz: "59302", ort: "Oelde", lat: 51.8289, lon: 8.1472 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1769,
    website: "https://www.potts.de",
  },
  "Brauerei im Füchschen": {
    stammhaus: { strasse: "Ratinger Straße 28", plz: "40213", ort: "Düsseldorf", lat: 51.2278, lon: 6.7897 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1848,
    website: "https://www.fuechschen.de",
  },
  "Brauerei Schumacher": {
    stammhaus: { strasse: "Oststraße 123", plz: "40210", ort: "Düsseldorf", lat: 51.2215, lon: 6.7924 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1838,
    website: "https://www.schumacher-alt.de",
  },
  "Brauerei Päffgen": {
    stammhaus: { strasse: "Friesenstraße 64–66", plz: "50670", ort: "Köln", lat: 50.9428, lon: 6.9412 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1883,
    website: "https://www.paeffgen-koelsch.de",
  },
  "Krombacher Brauerei": {
    stammhaus: { strasse: "Krombacher Brauerei", plz: "57223", ort: "Kreuztal-Krombach", lat: 50.9697, lon: 7.8983 },
    geschaeftsfuehrung: "Bernhard Schadeberg",
    absatz_hl: 6200000,
    gruendung: 1803,
    website: "https://www.krombacher.de",
  },
  "Warsteiner Brauerei Haus Cramer": {
    stammhaus: { strasse: "Hauptstraße 18", plz: "59581", ort: "Warstein", lat: 51.4449, lon: 8.3535 },
    geschaeftsfuehrung: "Albert Cramer",
    absatz_hl: null,
    gruendung: 1753,
    website: "https://www.warsteiner.de",
  },
  "Herforder Brauerei": {
    stammhaus: { strasse: "Herforder Straße 67", plz: "32120", ort: "Hiddenhausen", lat: 52.1711, lon: 8.6167 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1878,
    website: "https://www.herforder.de",
  },
  "Privatbrauerei Moritz Fiege": {
    stammhaus: { strasse: "Moritz-Fiege-Straße 1", plz: "44803", ort: "Bochum", lat: 51.4789, lon: 7.2167 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1878,
    website: "https://www.moritzfiege.de",
  },
  "König-Brauerei": {
    stammhaus: { strasse: "Königstraße 1", plz: "47259", ort: "Duisburg-Beeck", lat: 51.4908, lon: 6.7656 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1858,
    website: "https://www.koenig.de",
  },
  "Bolten-Brauerei": {
    stammhaus: { strasse: "Krefelder Straße 92", plz: "41352", ort: "Korschenbroich", lat: 51.1922, lon: 6.5133 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1266,
    website: "https://www.bolten.de",
  },
  "Brauerei Diebels": {
    stammhaus: { strasse: "Brauereistraße 1", plz: "47652", ort: "Issum", lat: 51.5367, lon: 6.4214 },
    geschaeftsfuehrung: null,
    absatz_hl: null,
    gruendung: 1878,
    website: "https://www.diebels.de",
  },
  "Brauerei C. & A. Veltins": {
    stammhaus: { strasse: "Veltinsstraße 1", plz: "59872", ort: "Meschede-Grevenstein", lat: 51.3492, lon: 8.2839 },
    geschaeftsfuehrung: "Susanne Veltins",
    absatz_hl: null,
    gruendung: 1824,
    website: "https://www.veltins.de",
  },
};
